// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmKqyBBb7fRNNl0jq04uxVcycI61NTPAA',
    appId: '1:322711153027:web:626ef4e59ca6ef4bcdeeb6',
    messagingSenderId: '322711153027',
    projectId: 'ecom-firebase-bb3dc',
    authDomain: 'ecom-firebase-bb3dc.firebaseapp.com',
    storageBucket: 'ecom-firebase-bb3dc.firebasestorage.app',
    measurementId: 'G-S6JRM8EYX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9r-2nv3sRiMhxhYqz1Atv-pTUkJ6hrI',
    appId: '1:322711153027:android:dde1d94a4c586bdbcdeeb6',
    messagingSenderId: '322711153027',
    projectId: 'ecom-firebase-bb3dc',
    storageBucket: 'ecom-firebase-bb3dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkU3oFWnT7r22XDKMYLbAh22R1dhc3QIs',
    appId: '1:322711153027:ios:6b0378431813fac9cdeeb6',
    messagingSenderId: '322711153027',
    projectId: 'ecom-firebase-bb3dc',
    storageBucket: 'ecom-firebase-bb3dc.firebasestorage.app',
    iosBundleId: 'com.example.ecomFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkU3oFWnT7r22XDKMYLbAh22R1dhc3QIs',
    appId: '1:322711153027:ios:6b0378431813fac9cdeeb6',
    messagingSenderId: '322711153027',
    projectId: 'ecom-firebase-bb3dc',
    storageBucket: 'ecom-firebase-bb3dc.firebasestorage.app',
    iosBundleId: 'com.example.ecomFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmKqyBBb7fRNNl0jq04uxVcycI61NTPAA',
    appId: '1:322711153027:web:2478cdd30b49c5facdeeb6',
    messagingSenderId: '322711153027',
    projectId: 'ecom-firebase-bb3dc',
    authDomain: 'ecom-firebase-bb3dc.firebaseapp.com',
    storageBucket: 'ecom-firebase-bb3dc.firebasestorage.app',
    measurementId: 'G-XYS495P6ZS',
  );
}
